name: Git Clone, Unzip, Install, and Run

on:
  push:
    branches:
      - main  # Jalankan setiap ada push di branch 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Clone the target repository
    - name: Clone RepositoryName repository
      run: |
        git clone https://github.com/ManzKeDua/runtod

    # Step 2: Navigate into the RepositoryName directory
    - name: Change directory to runtod 
      run: cd runtod

    # Step 3: Unzip manzpush.zip file inside the runtod folder
    - name: Unzip manzpush.zip
      run: |
        sudo apt-get install unzip  # Install unzip tool if not already installed
        unzip runtod/manzpush.zip -d ./runtod # Unzip manzpush.zip in the runtod directory

    # Step 4: Install npm dependencies
    - name: Install npm dependencies
      run: |
        cd manzpush
        npm install

    # Step 5: Start the npm application
    - name: Start the application
      run: |
        cd manzpush
        npm start
